amyyalex/simple-contribution

- index.html
I added my information using the template on the HTML page
> Added my contribution

- index.html
Thankyou for the awesome opportunity to let me contribute for the first time
> Thanks for being awesome

- index.html
> NazWebs contribution

- index.html
> AbhiJoshi-Info-card

- index.html
> Added my info

- app.js
Thanks for having a simple repo for a first contribution!
> Added Casey Charleston to contributors list

- app.js
- index.html
Thank you for give us chance to contribute in this project..
> Add Ashwin Dhangar to Contributor List

- app.js
- index.html
- style/style.css
> added my detail

- app.js
This is a simple contribution on my journey to Open Source Contribution
> Add <Adeshina-Olorogun> card info

- app.js
> Add Dayo Orunsolu to card info

- app.js
I added my information to the app.js file.
> added Motlatsi Moea information

- app.js
Kevin Crumbleton was added to the list!
> added Kevin Crumbleton info

- app.js
- index.html
Reverts amyyalex/simple-contribution#30
Conflicting files leading to deletion of card section when merged. (Issue check)
> Revert "Add my information"

- app.js
- index.html
Reverts amyyalex/simple-contribution#43
Issue check confirmed
> Revert "Revert "Add my information""

- app.js
- index.html
Reverts amyyalex/simple-contribution#44
Issue still surfaces (issue: Card container disappears when merged. Reverting back to original file)
> Revert "Revert "Revert "Add my information"""

- app.js
Add contact information for Caleb Nkunze
> content: Add info for Nkunze Caleb

- app.js
Added SQL and DevOps to my list of skills.
> updated my profession

- banner.js
- cardDetails.json
- index.html
- style/style.css
I have enhanced the banner design by incorporating a subtle animation that aligns with the existing color scheme and design aesthetics of the website. These changes have been implemented thoughtfully to ensure minimal impact on loading times and maintain readability. Additionally, I have made the design responsive, ensuring a seamless experience on small screens. While adhering to most of the requested elements, I've creatively integrated my design, resulting in a cohesive and harmonious overall appearance. I hope you like it! - Manu Arias
> Banner design

- .idea/.gitignore
- .idea/jpa-buddy.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/simple-contribution.iml
- .idea/vcs.xml
- cardDetails.json
Added my GitHub profile link, LinkedIn and mail address.
> added my details to card details json file

- README.md
Punctuation added to:
> This project is for both developers and non developers 
It is now changed to: 
> This project is for both developers and non-developers.
> Punctuation Branch 1

- .idea/.gitignore
- .idea/jpa-buddy.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/simple-contribution.iml
- .idea/vcs.xml
- cardDetails.json
Reverts amyyalex/simple-contribution#67
> Revert "added my details to card details json file"

- cardDetails.json
Add Wesley Waka to card Details
> add Wesley Waka

- cardDetails.json
> Chi's Update cardDetails.json

- cardDetails.json
- contribution.md
- index.html
> Improve contribution guide

- cardDetails.json
> add my informactions

- app.js
- cardDetails.json
- index.html
- style/style.css
This PR is for a issue 60, so I try to figure it out! 
You can search by name and order by alphabetic
> Search functionality

- app.js
- index.html
- style/style.css
Fixes #21 
pagination functionality is implemented using HTML, CSS, and JavaScript.
displays 10 cards per page.
For Quick Check of changes : https://lavanya-sathya.github.io/simple-contribution/
> pagination-added

- style/style.css
Fixes #82 
Visibility issue for medium sized screen is updated
https://lavanya-sathya.github.io/simple-contribution/
> search-element-visibility-issue

- app.js
- cardDetails.json
Added Sreekakulam Lohith card info and updated search filter.
> Updated Search Filter

- cardDetails.json
- contribution.md
feat(cardDetails.json): add tonybnya card info
docs(contribution.md): emphasize text to indicate the 2 ways for contributions
> feat(cardDetails.json): add tonybnya card info

- cardDetails.json
Add Sabeha Khan card info by modifying cardDetails.json
> Add Sabeha Khan card info

- contribution.md
In the "Go to carddetail.json file" part of  Step 5 in contribution.md fixed the spelling from "mmake" to "make".
> Fixed spelling in contribution.md

- cardDetails.json
> updated my details

- cardDetails.json
I added my profile to cardDetails.json file
> added my profile

- banner.js
- index.html
- style/banner.css
- style/style.css
Improved the banner design with a new animated design. Also changed the background and button color to a more appealing style. 
As this is my first pull request it was very fun to work on this project . . . .Thank You for the project!!!!!!
> #23 Improve banner design done

- cardDetails.json
All in open source africa program
> Add [Abdessamad Touzani Card's Detail]

- cardDetails.json
- index.html
added name with social media details: Brian Chebon information.
> Add Brian Chebon card info

- cardDetails.json
added the details of John Irem to the cardDetails.json file
> add rasine details

- README.md
Integrate a dynamic solution to fetch contributors' avatars from their GitHub profiles and display them in the Readme. This enhancement celebrates the diverse community contributing to the project, adding a personal touch to the documentation. By showcasing the faces behind the code, we aim to strengthen the sense of community and recognition for our invaluable contributors. Let's make our Readme reflect the vibrant and diverse community that drives the success of our open-source endeavor.
#87 Closes
> Add dynamic contributors' avatars to Readme Closes #87

- cardDetails.json
Did an edit of my card details.
> carddetails

- cardDetails.json
- index.html
I added only my contacts but, if I have free time, I try to add dark and light mode. So, firstly, I must customize color styles and create dark color styles which is pretty annoying, but I will do it.
> My Brunch 

- cardDetails.json
Added my details to the cardDetails.json file
> my simple contribution

- cardDetails.json
Added my details and famous quote to .json file
> Added card to carddetails.json

- README.md
- cardDetails.json
Hi, I am very much impressed with your project and what you are doing to help developers contribute to open source. While going through the README.md though I noticed a few errors and outdated information which I took the liberty to correct. 
Hope you go through them and see if they are okay to be merged.
> Edit readme

- cardDetails.json
I just added my info to the cardDetails.json file.
> Add Wesley Perrang card info

- cardDetails.json
Add Cephas Tokoli Card Details on this feature branch
> New contribution

- cardDetails.json
Created a section of my profile details using the template given in cardDetails.json
> Update my profile on cardDetails.json

- cardDetails.json
Except adding my info, I added two forgotten commas=)
> my first contribution

- cardDetails.json
- index.html
> my information

- cardDetails.json
Adds my name (Tenneh Kanneh), my profession, a quote I love, a twitter link, GitHub link, a LinkedIn link, and an email address to the cardDetails.json file.
> add-tennehkanneh

- cardDetails.json
Added card details for my self
> Added Itzel Bailon, my fav quote,and my socials to the json file

- cardDetails.json
> add my card details and fix structure JSON file (line 2)

- cardDetails.json
Added kenmusau information.
I also added a missing closing Curly brace and comma that a contributor had forgotten to add.
> add kenmusau information

- cardDetails.json
- style/style.css
1. Adjusted the margin bottom of the Footer
2. Created a hover effect on each of the cards of rgba(10, 3, 50, 0.227)
> Silvia branch

- style/style.css
This PR will add an underline text decoration to the navbar links
> Navlinks styling

- cardDetails.json
> Add Card Information

- index.html
- scss/navbar-btn.scss
- style/style.css
This update enhances the card component by introducing a hover animation effect that creates a dynamic and visually appealing shadow around the card.
1. **CSS Modifications**:
- **`.card` Class**:
- Added properties to handle the animation when the card is hovered over.
- **Hover Effects**:
- Implemented `box-shadow` properties to replace the background color animation for a smoother visual experience.
- Defined two keyframe animations (`clockwise` and `counterclockwise`) for a rotating shadow effect.
2. **Keyframe Animations**:
- **`@keyframes clockwise`**:
- Created an animation sequence to simulate a shadow moving in a clockwise direction around the card.
- **`@keyframes counterclockwise`**:
- Created a complementary animation to simulate a shadow moving in a counterclockwise …
> Added a single div hover animation on Cards

- cardDetails.json
> added details to cardDetails.json

- cardDetails.json
I added my information to the cardDetails.json file
> added my information to the cardDetails.json file

- index.html
[The fav icon was not visible. Now it is visible and works fine. Not a big issue to fix but i guess it's fine. :)
> Updated the Favicon

- cardDetails.json
> Information

- cardDetails.json
Added my information to cardDetails.json as part of my contribution to the project.
> card Details added

- cardDetails.json
Je viens d'ajouter mes informations sur le cardDetails.json
> A new contribution

- cardDetails.json
I included my name to the list of contributors
> Adding my name to the list of contributors

- cardDetails.json
> Add Idorenyin to Contributors list

- cardDetails.json
adding my information details on the card details.json
> Ziphozenkosi

- cardDetails.json
**Pull Request Description:**
- Added my personal information
- Included my profile's Linktree
> Added my personal informations and my profiles link tree

- cardDetails.json
> Added my information

- cardDetails.json
> feat: added nathan

- cardDetails.json
added my details to the simple card
> add my details to json

- cardDetails.json
> Add Osama rabea card info

- cardDetails.json
- Added Derrick Ampire info
- Fixed missing comma on line 1523 in the `cardDetails.json` file
> Add Derrick Ampire card info

- cardDetails.json
I add a bio section to the file
> Added Samuel details to cardDetails.json

- cardDetails.json
added my details : name , favorite quote, and social media details.
> added khaulanauman details

- cardDetails.json
Added my details to the repository.
> added Richard Callaby

- cardDetails.json
> add my details to cardDetails.json file

- cardDetails.json
> added farzan ullah information

- cardDetails.json
Added new card for myself in cardDetails.json.
> Modified cardDetails.json (new card)

- style/style.css
Navbar Animations: Added hover animations to menu items to enhance interactivity.
Themed Navbar: Styled the navbar to align with the website's overall theme, ensuring visual consistency.
Card Hover Effects: Improved card hover effects with engaging animations such as shadow effects, slight zoom-ins, and background color transitions.
> Enhance Navbar and Card Hover Animations to Match Website Theme.

- index.html
I changed the target link attribute from "blank" to "self"
> Change the target link

- cardDetails.json
Added my details to the CardDetails.json file
> Update: Added info on cardDetails

- cardDetails.json
> Add Usiwo Sonia Uyouyou to Contributors list

- cardDetails.json
Minor Issue Fixed + New Card Object
> minor comma fix + new card

- cardDetails.json
> Add irsyad212

- style/style.css
Fixes #295
Made some changes in Cards Css
> Implemented responsive design for Mobile veiw 

- cardDetails.json
- index.html
I have included my personal details to the community.
> add my details

- cardDetails.json
Agradecimiento por mi primera contribución en Open Source
ha sido una experiencia increíble y estoy muy feliz de haber dado este primer paso. Gracias al equipo por su paciencia y por la oportunidad de aprender y colaborar. ¡Espero seguir contribuyendo y creciendo junto a esta comunidad!
> agregue mi informacion
